# Generated by Django 4.2.17 on 2025-10-05 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_manualdeposit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='config',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('add_money', 'Add Money'), ('withdraw', 'Withdraw'), ('transfer', 'Transfer'), ('sale', 'Sale'), ('commission', 'Commission'), ('admin_fee', 'Admin Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
