# Generated by Django 4.2.17 on 2025-10-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_options_alter_paymentmethod_config_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='config',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='instructions',
            field=models.TextField(blank=True, help_text="For manual methods, provide instructions for the user (e.g., 'Use your username as reference')."),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('auto', 'Automatic Gateway (e.g., Monnify)'), ('manual', 'Manual Bank Transfer')], default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
