# Generated by Django 4.2.17 on 2025-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira (NGN)'), ('USD', 'US Dollar (USD)')], default='NGN', max_length=3)),
                ('currency_rate', models.DecimalField(decimal_places=4, default=1.0, help_text='Conversion rate from base currency (NGN) to USD', max_digits=10)),
                ('add_money_fee_pct', models.DecimalField(decimal_places=2, default=1.5, help_text='Percentage fee for adding money', max_digits=5)),
                ('transfer_fee_pct', models.DecimalField(decimal_places=2, default=0.5, help_text='Percentage fee for transfers', max_digits=5)),
                ('withdraw_fee_pct', models.DecimalField(decimal_places=2, default=2.0, help_text='Percentage fee for withdrawals', max_digits=5)),
                ('mentorship_fee_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage fee for mentorship payments', max_digits=5)),
                ('default_commission_pct', models.DecimalField(decimal_places=2, default=20.0, help_text='Default commission percentage for affiliate sales', max_digits=5)),
                ('pause_course_uploading', models.BooleanField(default=False, help_text='Pause new course uploads')),
                ('pause_gigs_uploading', models.BooleanField(default=False, help_text='Pause new gigs/jobs uploads')),
                ('pause_affiliates', models.BooleanField(default=False, help_text='Pause affiliate program')),
                ('site_title', models.CharField(default='Vinaji NG', max_length=200)),
                ('site_description', models.TextField(blank=True, help_text='Site meta description')),
                ('contact_email', models.EmailField(default='support@vinaji.com', max_length=254)),
                ('legal_text', models.TextField(blank=True, help_text='Terms of service, privacy policy, etc.')),
                ('default_subscription_prices', models.JSONField(default=dict, help_text='JSON with default prices for subscription plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
