# Generated by Django 4.2.17 on 2025-10-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('action_url', models.URLField(blank=True)),
                ('action_text', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('show_popup', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='deposit_mode',
            field=models.CharField(choices=[('manual', 'Manual Approval'), ('auto', 'Auto Process')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='monnify_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='monnify_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='withdrawal_mode',
            field=models.CharField(choices=[('manual', 'Manual Approval'), ('auto', 'Auto Process')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='add_money_fee_pct',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='currency_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='default_commission_pct',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='default_subscription_prices',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='legal_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mentorship_fee_pct',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='pause_affiliates',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='pause_course_uploading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='pause_gigs_uploading',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='transfer_fee_pct',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='withdraw_fee_pct',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('job', 'Job'), ('course', 'Course'), ('product', 'Product'), ('blog', 'Blog')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'category_type')},
            },
        ),
    ]
