# Generated by Django 4.2.17 on 2025-10-05 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_core', '0002_adminnotification_sitesetting_deposit_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonnifyBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monnify Bank',
                'verbose_name_plural': 'Monnify Banks',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='account_reference_prefix',
            field=models.CharField(default='VINAJI', help_text='Prefix for account references', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_bank_code',
            field=models.CharField(blank=True, help_text='Default bank for virtual accounts', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_payment_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_payment_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='manual_payment_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='monnify_base_url',
            field=models.CharField(default='https://api.monnify.com', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='monnify_contract_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ManualDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('screenshot', models.ImageField(upload_to='deposit_screenshots/')),
                ('depositor_name', models.CharField(help_text='Name of person who made the deposit', max_length=100)),
                ('deposit_date', models.DateTimeField(help_text='Date and time when deposit was made')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviewed_deposits', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_manual_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manual Deposit',
                'verbose_name_plural': 'Manual Deposits',
            },
        ),
    ]
