# Generated by Django 4.2.17 on 2025-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0003_monnifybank_sitesetting_account_reference_prefix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='manual_payment_account_name',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='manual_payment_account_number',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='manual_payment_bank_name',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='paystack_public_key',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='paystack_secret_key',
        ),
        migrations.DeleteModel(
            name='ManualDeposit',
        ),
    ]
