# Generated by Django 4.2.17 on 2025-10-04 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_core', '0002_adminnotification_sitesetting_deposit_mode_and_more'),
        ('jobs', '0003_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'job'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='site_core.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
