# Generated by Django 5.2.7 on 2025-10-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_signup_reward', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed amount rewarded for each successful referral signup', max_digits=10)),
                ('referral_commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text="Percentage commission on referred user's transactions", max_digits=5)),
                ('job_posting_fee_rate', models.DecimalField(decimal_places=2, default=2.0, help_text='Percentage fee on job postings', max_digits=5)),
                ('course_sale_fee_rate', models.DecimalField(decimal_places=2, default=3.0, help_text='Percentage fee on course sales', max_digits=5)),
                ('product_sale_fee_rate', models.DecimalField(decimal_places=2, default=2.5, help_text='Percentage fee on product sales', max_digits=5)),
                ('mentorship_fee_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Percentage fee on mentorship enrollments', max_digits=5)),
                ('withdrawal_fee_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='Percentage fee on withdrawals', max_digits=5)),
                ('withdrawal_fixed_fee', models.DecimalField(decimal_places=2, default=50.0, help_text='Fixed fee on withdrawals (in addition to percentage)', max_digits=10)),
                ('transfer_fee_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Percentage fee on transfers', max_digits=5)),
                ('min_withdrawal_amount', models.DecimalField(decimal_places=2, default=1000.0, help_text='Minimum amount for withdrawals', max_digits=10)),
                ('min_commission_payout', models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum commission amount before payout', max_digits=10)),
                ('auto_approve_commissions', models.BooleanField(default=False, help_text='Automatically approve affiliate commissions')),
                ('commission_payout_delay_days', models.PositiveIntegerField(default=7, help_text='Days to wait before commission payout')),
            ],
            options={
                'verbose_name': 'Affiliate Settings',
                'verbose_name_plural': 'Affiliate Settings',
            },
        ),
    ]
