# Generated by Django 4.2.17 on 2025-10-04 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='my_favorite_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
