# Generated by Django 4.2.17 on 2025-10-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0002_adminnotification_sitesetting_deposit_mode_and_more'),
        ('courses', '0002_alter_course_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'course'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='site_core.category'),
        ),
    ]
