# Generated by Django 4.2.17 on 2025-10-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_core', '0002_adminnotification_sitesetting_deposit_mode_and_more'),
        ('products', '0002_productimage_promocode_product_features_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category_type': 'product'}, on_delete=django.db.models.deletion.CASCADE, related_name='products_category', to='site_core.category'),
        ),
    ]
